name: Backend CI/CD

on:
  push:
    branches: [ UnieventosBackend ]

jobs:
  sonar-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Build and test
        working-directory: Backend/UnieventosBackend
        run: ./gradlew clean build test

      - name: SonarCloud Analysis
        working-directory: Backend/UnieventosBackend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_BACK }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
